---
Resources:
  devskondalalinux:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-223f945a"
      InstanceType: "m5.2xlarge"
      KeyName: "keyPresalesNA_Prod_Demo_2020.pem"
      SecurityGroups:
        - "sgPresalesNA_Dev_2017_10_vpn_north_america"

      NetworkInterfaces:
        - NetworkInterfaceId: !Ref MyAppNetworkInterface
          DeviceIndex: 0
  MyAppNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: "subnet-e7f17d81"



