---
Resources:
  devskondalalinux:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-223f945a"
      InstanceType: "m5.2xlarge"
      KeyName: "keyPresalesNA_Prod_Demo_2020"


      NetworkInterfaces:
        - NetworkInterfaceId: !Ref MyAppNetworkInterface
          DeviceIndex: 0
  MyAppNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: "subnet-e7f17d81"
      GroupSet:
        - "sg-1eac0363"



