---
Parameters:
  InstanceType:
    Type: String
    AllowedValues:
      - t1.micro
      - t2.nano



Resources:
  devskondalalinux:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-223f945a"
      InstanceType: !Ref InstanceType
      KeyName: "keyPresalesNA_Prod_Demo_2020"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50

      NetworkInterfaces:
        - NetworkInterfaceId: !Ref MyAppNetworkInterface
          DeviceIndex: 0
  MyAppNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: "subnet-e7f17d81"
      GroupSet:
        - "sg-1eac0363"



